
version: '3'

services:

  bot:
    image: spicycherrypirate/leet-bot:latest
  
  db:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: